# -*- coding: utf-8 -*-
"""PyhtonAss_10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1O-IM6EV-8tu_PYJwFvWf2327LzwPgaxg

Q1. Python | Ways to remove a key from dictionary
"""

Test_Dict = {"Omkar": 21, "Sahil": 20 , "Shubham": 21}

print("The original dictionary is :",Test_Dict)

Remove =input("Enter the key u want to remove:")
del Test_Dict[Remove]
print(Test_Dict)

"""Q2. Ways to sort list of dictionaries by values in Python – Using itemgetter"""

from operator import itemgetter

Test_list =[{"Name":"Omkar","Location":"Mumbai","Age":21},
            {"Name":"Shubham","Location": "Pune","Age":22},
            {"Name": "Sahil", "Location":"Mumbai","Age":20}]


print("The sorted list is:")
print(sorted(Test_list, key=itemgetter("Age")))

"""Q3. Ways to sort list of dictionaries by values in Python – Using lambda function"""

Test_list =[{"Name":"Omkar","Location":"Mumbai","Age":21},
            {"Name":"Shubham","Location": "Pune","Age":22},
            {"Name": "Sahil", "Location":"Mumbai","Age":20}]

print("The original list is:")
print(sorted(Test_list, key=lambda i: i['Age']))

"""Q4. Python | Merging two Dictionaries"""

Dict_1 = {"Omkar": 21,"Sahil": 20, "Shubham": 21}
Dict_2 = {"Patade": "Mumbai","Lade": "Mumbai","Shedekar":"Pune"}

print(Dict_2.update(Dict_1))
print(Dict_2)

"""Q5. Python – Convert key-values list to flat dictionary"""

Dict_1 = {'Ranks': [1, 2, 3], 'alphabet': ['A', 'B', 'C']}

print("The original dictionry is: " ,Dict_1)

flat_Dict =dict(zip(Dict_1["Ranks"], Dict_1["alphabet"]))

print(flat_Dict)

"""Q6. Python – Insertion at the beginning in OrderedDict"""

from collections import OrderedDict


Dict_1 = OrderedDict([("Omkar" ,'21'),("Sahil" ,'20'), ("Shubham", '21')])
Dict_1.update({"dsnods": '02'})
Dict_1.move_to_end("dsnods", last = False)


print("New dictionary is: " ,Dict_1)

"""Q7. Python | Check order of character in string using OrderedDict( )"""

from collections import OrderedDict

def checkOrder(string, pattern): 
    dic = OrderedDict.fromkeys(string) 
    ptr = 0
    for key,value in dic.items(): 
        if (key == pattern[ptr]): 
            ptr = ptr + 1
        if (ptr == (len(pattern))): 
            return 'True'
    return 'False'

string = 'Hello Welcome to the python'
pattern = 'on'
print (checkOrder(string,pattern))

string2= 'ineuron'
pattern2= 'rn'
print (checkOrder(string2,pattern2))

"""Q8.Dictionary and counter in Python to find winner of election"""

from collections import Counter

def winner(input):
	votes = Counter(input)

	Dict_1 = {}

	for value in votes.values():
		Dict_1[value] = []

	for (key,value) in votes.items():
		Dict_1[value].append(key)

	maxVote = sorted(Dict_1.keys(),reverse=True)[0]
	if len(Dict_1[maxVote])>1:
		print (sorted(Dict_1[maxVote])[0])
	else:
		print (Dict_1[maxVote][0])

if __name__ == "__main__":
	input =['omkar','shubham','sahil','sahil',
			'shubham','amey','shubham','shubham',
			'omkar','siddhesh','shubham','siddhesh',
			'shubham','amey']
	winner(input)

"""Q9.Python – Append Dictionary Keys and Values ( In order ) in dictionary"""

Dict_1 = {"Gfg" : 1, "is" :  3, "Best" : 2}
 

print("The original dictionary is : " + str(Dict_1))
 
res = list(Dict_1.keys()) + list(Dict_1.values())
 
print("The ordered keys and values : " + str(res))

"""Q10.Python | Sort Python Dictionaries by Key or Value"""

from collections import OrderedDict
 
dict_1 = {'Omkar': '20', 'Shubham': '21',
        'Sahil': '20', 'Siddhesh': '22', 'Amey': '19'}
dict1 = OrderedDict(sorted(dict_1.items()))
print(dict1)