# -*- coding: utf-8 -*-
"""PythonAss_9ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pDno9qN4pvUBv4pxO62j6zfyFYqE_kq-

Q1 Python – Replace multiple words with K
"""

string =input("Enter the string :")
s =input("Enter the words which you want to replace: ")
print("The original string is : " , string)


replace_word ="K"
New_string = ' '.join([replace_word if i in s else i for i in string.split()])
  
print("new string after multiple replace : " , New_string)

"""Q2. Python | Permutation of a given string using inbuilt function"""

from itertools import permutations
import string

string1 = "NOP"
a = string.ascii_letters
p = permutations(string1)

d = []
for i in list(p):

	
	if (i not in d):
		d.append(i)
		print(''.join(i))

"""Q3. Python | Check for URL in a String"""

import re

string ="youtube link :https://www.youtube.com/"

string_url = re.findall('http[s]?://(?:[a-zA-Z]|[0-9]|[$-_@.&+]|[!*\(\),]|(?:%[0-9a-fA-F][0-9a-fA-F]))+'
,string)

print(string_url)

"""Q4.Execute a String of Code in Python"""

string ="""s = 1+2
print(s)"""

exec(string)

"""Q5. String slicing in Python to rotate a string"""

def rotate_string(string1,d):

  Lfirst =string1[0:d]
  Lsecond =string1[d:]
  Rfirst = string1[0: len(string1)-d]
  Rsecond  = string1[len(string1)-d : ]

  print("The left rotation is : ",(Lsecond+Lfirst) )
  print("The right rotaion is: " ,(Rsecond+Rfirst) )

string = "Helloworldwelcome"
d=4
rotate_string(string,d)

"""Q6.String slicing in Python to check if a string can become empty by recursive deletion

"""

def check_empty(string,sub_string):

  while(len(string) != 0):
    try:
      idx = string.index(sub_string)
    except ValueError:
      return 'False'

    
    string=string[0:idx] + string[idx + len(sub_string) :]
    print(string)

  return 'sthe string is empty'

if __name__== '__main__':
  string = input("enter the string : ")

  sub_string=input("enter the substring: ")

  print(check_empty(string,sub_string))

"""Q7. Python Counter| Find all duplicate characters in string"""

string = "abcabcdgfgjgsdhhamsn";  
   
print("The duplicate characters in a given string: ");  
for i in range(0, len(string)):  
    count = 1;  
    for j in range(i+1, len(string)):  
        if(string[i] == string[j] and string[i] != ' '):  
            count = count + 1;  
            string = string[:j] + '0' + string[j+1:];  
   
    if(count > 1 and string[i] != '0'):  
        print(string[i]);

"""Q8. Python – Replace all occurrences of a substring in a string"""

string = input("Enter the string: ")
sub_string = input("Enter the cha which you want to replace: ")
s = input("the cha: ")
string = string.replace(sub_string, s)
print(string)

"""Q9.python – extract unique values dictionary values"""

dict1 = {'num1' : [1, 3, 5, 4],
             'num2' : [4, 6, 8, 10],
             'num3' : [6, 12, 4 ,8],
             'num4' : [5, 7, 2]}
  
res = list(sorted({ele for val in dict1.values() for ele in val}))
  
print("The unique values are : " , res)

"""Q10.Python program to find the sum of all items in a dictionary"""

def sum(dict):
	sum = 0
	for i in dict.values():
		sum = sum + i

	return sum


dict = {'a': 100, 'b': 100, 'c': 100}
print("Sum is :", sum(dict))

